"use client";

import { DBImage } from "@/lib/db/schema";
import Image from "next/image";
import { MatchBadge } from "./match-badge";
import { Card } from "./ui/card";

export function ImageCard({
  image,
  similarity,
}: {
  image: DBImage;
  similarity?: number;
}) {
  return (
    <Card
      key={image.id}
      className="h-[250px] md:h-[450px] relative group rounded-lg overflow-hidden"
    >
      <div className="absolute inset-0 z-10">
        <span className="sr-only">View image</span>
      </div>
      <Image
        src={image.path}
        alt={image.title}
        width={300}
        height={450}
        className="w-full h-full object-cover transition-transform group-hover:scale-105"
      />
      <div className="absolute inset-0 bg-zinc-900/70 group-hover:opacity-100 opacity-0 transition-opacity flex flex-col items-center justify-center p-6 text-white text-center">
        <h3 className="text-xl font-semibold">{image.title}</h3>
        <p className="hidden md:block text-sm mt-2 overflow-y-hidden">
          {image.description}
        </p>
        <p className="hidden md:block text-xs font-medium text-gray-100 italic mt-4">
          Metadata Generated by GPT-4o
        </p>
      </div>
      {similarity ? (
        <div className="py-2 z-10 absolute bottom-2 left-2">
          <MatchBadge
            type={similarity === 1 ? "direct" : "semantic"}
            similarity={similarity}
          />
        </div>
      ) : null}
    </Card>
  );
}
